services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.56.1-noble
    platform: linux/amd64
    working_dir: /app
    volumes:
      - .:/app
      - playwright-node-modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  playwright-node-modules:
